### Basic data types
(http://cs231n.github.io/python-numpy-tutorial/)

In [12]:
x = 3
print type(x)

y = 2.5
print type(y)

t = True
f = False
print type(t)
print t and f

hello = 'hello'
world = 'world'
print hello
print len(hello)
print hello + ' ' + world

<type 'int'>
<type 'float'>
<type 'bool'>
False
hello
5
hello world


In [18]:
s = 'Hello'
print s.capitalize()
print s.upper()
print s.rjust(7)
print '   blah '.strip()

Hello
HELLO
  Hello
blah


### Containers

In [27]:
xs = [3, 1, 2]
print xs, xs[2]
print xs[-1]
xs[2] = 'foo'
print xs
xs.append('bar')
print xs
x = xs.pop()
print xs, x

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
[3, 1, 'foo'] bar


### Slicing

In [36]:
nums = range(5)
print nums
print nums[2:4]    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print nums[2:]     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print nums[:2]     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print nums[:]      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print nums[:-1]    # Slice indices can be negative; prints ["0, 1, 2, 3]"

nums[2:4] = [8, 9] # Assign a new sublist to a slice
print nums         # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


### Loops

In [39]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print animal
    
for idx, animal in enumerate(animals):
    print '#%d: %s' % (idx + 1, animal)

cat
dog
monkey
#1: cat
#2: dog
#3: monkey


### List Comprehensions

In [42]:
nums = [0, 1, 2, 3, 4]
squares = []

# using a loop
for x in nums:
    squares.append(x**2)

print squares

# using a list comprehension
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print squares   # Prints [0, 1, 4, 9, 16]

# list comprehensions can also contain conditions
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print even_squares  # Prints "[0, 4, 16]"

[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16]
[0, 4, 16]


### Dictionaries

In [43]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print d['cat']       # Get an entry from a dictionary; prints "cute"
print 'cat' in d     # Check if a dictionary has a given key; prints "True"
d['fish'] = 'wet'    # Set an entry in a dictionary
print d['fish']      # Prints "wet"
# print d['monkey']  # KeyError: 'monkey' not a key of d
print d.get('monkey', 'N/A')  # Get an element with a default; prints "N/A"
print d.get('fish', 'N/A')    # Get an element with a default; prints "wet"
del d['fish']        # Remove an element from a dictionary
print d.get('fish', 'N/A') # "fish" is no longer a key; prints "N/A"

cute
True
wet
N/A
wet
N/A


Loops

In [47]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print 'A %s has %d legs' % (animal, legs)

print

# Access keys and corresponding values
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.iteritems():
    print 'A %s has %d legs' % (animal, legs)

A person has 2 legs
A spider has 8 legs
A cat has 4 legs

A person has 2 legs
A spider has 8 legs
A cat has 4 legs


Dictionary Comprehensions

In [48]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print even_num_to_square  # Prints "{0: 0, 2: 4, 4: 16}"

{0: 0, 2: 4, 4: 16}


### Sets

In [49]:
animals = {'cat', 'dog'}
print 'cat' in animals   # Check if an element is in a set; prints "True"
print 'fish' in animals  # prints "False"
animals.add('fish')      # Add an element to a set
print 'fish' in animals  # Prints "True"
print len(animals)       # Number of elements in a set; prints "3"
animals.add('cat')       # Adding an element that is already in the set does nothing
print len(animals)       # Prints "3"
animals.remove('cat')    # Remove an element from a set
print len(animals)       # Prints "2"

True
False
True
3
3
2


Loops & Comprehensions

In [56]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print '#%d: %s' % (idx + 1, animal)
# Prints "#1: fish", "#2: dog", "#3: cat"
print

from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print nums

#1: fish
#2: dog
#3: cat

set([0, 1, 2, 3, 4, 5])


### Tuples

In [57]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)       # Create a tuple
print type(t)    # Prints "<type 'tuple'>"
print d[t]       # Prints "5"
print d[(1, 2)]  # Prints "1"

<type 'tuple'>
5
1


### Functions

In [58]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'
    
for x in [-1, 0, 1]:
    print sign(x)

negative
zero
positive


Optional arguments

In [59]:
def hello(name, loud=False):
    if loud:
        print 'HELLO, %s!' % name.upper()
    else:
        print 'Hello, %s' % name

hello('Bob') # Prints "Hello, Bob"
hello('Fred', loud=True)  # Prints "HELLO, FRED!"

Hello, Bob
HELLO, FRED!


### Classes

In [65]:
class Greeter:
    # Constructor
    def __init__(self, name):
        self.name = name
        
    def greet(self, loud=False):
        if loud:
            print 'HELLO, %s!' % self.name.upper()
        else:
            print 'Hello, %s' % self.name
        
g = Greeter('Fred')
g.greet()
g.greet(loud = True)

Hello, Fred
HELLO, FRED!


## Numpy
### Arrays
We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [75]:
import numpy as np

a = np.array([1, 2, 3])  # Create a rank 1 array
print type(a)
print a.shape

print a[0], a[1], a[2]   # Prints "1 2 3"

a[0] = 5
print a

b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print b.shape

print b[0, 0], b[0, 1], b[1, 0]   # Prints "1 2 4"

<type 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


Numpy also provides many functions to create arrays:

In [83]:
a = np.zeros((2, 2))
print a

print

b = np.ones((1, 2))
print b

print

c = np.full((2, 2), 7)
print c
print type(c)

print

d = np.eye(2)
print d

print

e = np.random.random((2, 2))
print e

[[ 0.  0.]
 [ 0.  0.]]

[[ 1.  1.]]

[[ 7.  7.]
 [ 7.  7.]]
<type 'numpy.ndarray'>

[[ 1.  0.]
 [ 0.  1.]]

[[ 0.7088804   0.5320293 ]
 [ 0.49587987  0.90402987]]


### Array Indexing

In [84]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print a[0, 1]   # Prints "2"
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print a[0, 1]   # Prints "77"

2
77


### Boolean Array Indexing

In [85]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print bool_idx      # Prints "[[False False]
                    #          [ True  True]
                    #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print a[bool_idx]  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print a[a > 2]     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
